### ISSUE TITLE
404 on all splunk.com links

### ISSUE THREAD

**Issue by omueller** [ZachChristensen28/TA-opnsense#108]
### Bug description

Hi, 

Just a short message to let you know that per today (20231105) all your splunk.com related links under https://splunk-opnsense-ta.ztsplunker.com are returning 404 errors: 

https://splunkbase.splunk.com/app/4538/ -> 404
https://splunkbase.splunk.com/app/5372/ -> 404

Not sure if it's a temporary issue or not. 
Best regards, Olivier

### Related links

-

### TA-opnsense Version

-

### Splunk Version

-

### OPNsense Version

-

**Comment by omueller** [comment]
Hi @ZachChristensen28, this seems to take some time, I hope you will manage to find a solution, even if it requires a project rename or something similar.   Good luck & best regards !

**Comment by omueller** [comment]
Do you think there will be a solution @ZachChristensen28  ?  A short update would be very appreciated, as we'd need to setup Splunk Forwarder on several OPNsense devices, and via an "official" plugin it would be best.   Alternative would be via a manual setup of the freebsd-forwarder via ssh, but it would most probably not survive an upgrade.  Thanks!

**Comment by ZachChristensen28** [comment]
Unfortunately, my hands are tied. They have not provided me with any timeframes for this app to be revealed on Splunkbase again. 

However, the same package that was published on Splunkbase, is the same package you can find in the current [release (TA-opnsense-1.5.4.tar.gz)](https://github.com/ZachChristensen28/TA-opnsense/releases/tag/v1.5.4).

This package goes through the same app vetting process Splunkbase has.

**Comment by omueller** [comment]
Thanks a lot @ZachChristensen28, I'll start with this then :)

**Comment by d3pr3cat3d** [comment]
Hi @ZachChristensen28, I would really like to see this in Splunkbase.

**Comment by ZachChristensen28** [comment]
This will be back up on Splunkbase within the next few days. This repo will soon be transferred to another organization (https://rba.community)
