### ISSUE TITLE
TA references lookup that it does not contain

### ISSUE THREAD

**Issue by xpac1985** [ZachChristensen28/TA-opnsense#13]
Hey,

first - thanks for your work on this :)
After installing the TA on a regular, non ES SH, I noticed that it causes an error on each search
`Could not load lookup=LOOKUP-http_status`

This is due to this line, that references the http_status lookup that is not contained in this app, but in the CIM app.

https://github.com/ZachChristensen28/TA-opnsense/blob/ded9996101ea7c222a489ec13720e626376e186c/default/props.conf#L122

I'm not exactly sure what the best way would be to deal with this - it could be simply removed, losing some informaton. It could be copied from the CIM app - the list is unlikely going to change in the future - and I guess that's what I'd recommend so the TA is usable for non-CIM users without error messages.

**Comment by ZachChristensen28** [comment]
Good point. I would normally recommend to just install the CIM app, however, it would be good to remove any dependencies for those who do not wish to use that app. I'll get that pushed out here soon after I run some tests.
