### ISSUE TITLE
HAProxy Plugin

### ISSUE THREAD

**Issue by a2tf** [ZachChristensen28/TA-opnsense#31]
Hi

We are using the HAProxy Plugin with opnsense. As we need the data in splunk, I would extend this add-on with my haproxy config. Would it be appreciated if I make a pull request afterwards or is it not intended to be in this add-on?

Thanks for your feedback.

Andi

**Comment by ZachChristensen28** [comment]
Yes, please make a pull request and I'll get it added to the next release. Thanks for being willing to contribute!
