### ISSUE TITLE
opnsense_icmp_6 regex is broken since opnsense 19.7

### ISSUE THREAD

**Issue by chaispaquichui** [ZachChristensen28/TA-opnsense#4]
Since opnsense 19.7, there is change in the format of icmpv6 logs

before : 

opnsense.appartement.me filterlog: 30,,,0,pppoe0,match,pass,in,6,0xc0,0x00000,255,**ICMPv6**,58,64,fe80::d2f0:dbff:fe85:2000,ff02::1,

now : 

OPNsense filterlog: 23,,,0,em0_vlan10,match,pass,out,6,0x00,0x00000,255,**ipv6-icmp**,58,24,fe80::5054:ff:fecd:65ea,fe80::c00f:f0ff:fea3:7746,

The regex is broken since it looks for the actual word "ICMPv6" in the log

this regex solves the problem : 

`filterlog\:\s+(?:[^\,]*\,){8}(6)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,(ICMPv6|ipv6-icmp)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,`

**Comment by chaispaquichui** [comment]
Same problem with UDP. The UDP keyword is not capitalized anymore : 

filterlog: 83,,,0,pppoe0,match,pass,out,6,0x00,0x00000,64,udp,17,50,2a02:a03f:4400:d432:f053:29c:69a4:2619,2001:503:eea3::30,52595,53,50

The new regex : 

filterlog\:\s+(?:[^\,]*\,){8}(6)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,(UDP|udp)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,([^\,]*)\,(\S*)

**Comment by ZachChristensen28** [comment]
I have updated the regex. Thanks for catching that!
